<?php

declare(strict_types=1);

namespace App\Core\Database\seeders;

use App\Core\App\KernelCli;
use App\Core\Repositories\Geoip\CountryRepositoryInterface;
use Illuminate\Container\Container;

class CountrySeeder
{
    private CountryRepositoryInterface $repository;
    private KernelCli $kernel;
    private Container $container;
    private $data = [
    ["country_id"=>1, "name"=>"Afghanistan","iso_code_2"=>"AF","iso_code_3"=>"AFG","status" => 0],
    ["country_id"=>2, "name"=>"Albania","iso_code_2"=>"AL","iso_code_3"=>"ALB","status" => 0],
    ["country_id"=>3, "name"=>"Algeria","iso_code_2"=>"DZ","iso_code_3"=>"DZA","status" => 0],
    ["country_id"=>4, "name"=> "American Samoa", "iso_code_2" => "AS", "iso_code_3"=>"ASM","status" => 0],
    ["country_id"=>5, "name"=>"Andorra","iso_code_2"=>"AD","iso_code_3"=>"AND","status" => 0],
    ["country_id"=>6, "name"=>"Angola","iso_code_2"=>"AO","iso_code_3"=>"AGO","status" => 0],
    ["country_id"=>7, "name"=>"Anguilla","iso_code_2"=>"AI","iso_code_3"=>"AIA","status" => 0],
    ["country_id"=>8, "name"=>"Antarctica","iso_code_2"=>"AQ","iso_code_3"=>"ATA","status" => 0],
    ["country_id"=>9, "name"=>"Antigua and Barbuda","iso_code_2"=>"AG","iso_code_3"=>"ATG","status" => 0],
    ["country_id"=>10, "name"=>"Argentina","iso_code_2"=>"AR","iso_code_3"=>"ARG","status" => 0],
    ["country_id"=>11, "name"=>"Armenia","iso_code_2"=>"AM","iso_code_3"=>"ARM","status" => 0],
    ["country_id"=>12, "name"=>"Aruba","iso_code_2"=>"AW","iso_code_3"=>"ABW","status" => 0],
    ["country_id"=>13, "name"=>"Australia","iso_code_2"=>"AU","iso_code_3"=>"AUS","status" => 0],
    ["country_id"=>14, "name"=>"Austria","iso_code_2"=>"AT","iso_code_3"=>"AUT","status" => 0],
    ["country_id"=>15, "name"=>"Azerbaijan","iso_code_2"=>"AZ","iso_code_3"=>"AZE","status" => 0],
    ["country_id"=>16, "name"=>"Bahamas","iso_code_2"=>"BS","iso_code_3"=>"BHS","status" => 0],
    ["country_id"=>17, "name"=>"Bahrain","iso_code_2"=>"BH","iso_code_3"=>"BHR","status" => 0],
    ["country_id"=>18, "name"=>"Bangladesh","iso_code_2"=>"BD","iso_code_3"=>"BGD","status" => 0],
    ["country_id"=>19, "name"=>"Barbados","iso_code_2"=>"BB","iso_code_3"=>"BRB","status" => 0],
    ["country_id"=>20, "name"=>"Belarus","iso_code_2"=>"BY","iso_code_3"=>"BLR","status" => 0],
    ["country_id"=>21, "name"=>"Belgium","iso_code_2"=>"BE","iso_code_3"=>"BEL","status" => 0],
    ["country_id"=>22, "name"=>"Belize","iso_code_2"=>"BZ","iso_code_3"=>"BLZ","status" => 0],
    ["country_id"=>23, "name"=>"Benin","iso_code_2"=>"BJ","iso_code_3"=>"BEN","status" => 0],
    ["country_id"=>24, "name"=>"Bermuda","iso_code_2"=>"BM","iso_code_3"=>"BMU","status" => 0],
    ["country_id"=>25, "name"=>"Bhutan","iso_code_2"=>"BT","iso_code_3"=>"BTN","status" => 0],
    ["country_id"=>26, "name"=>"Bolivia","iso_code_2"=>"BO","iso_code_3"=>"BOL","status" => 0],
    ["country_id"=>27, "name"=>"Bosnia and Herzegovina","iso_code_2"=>"BA","iso_code_3"=>"BIH","status" => 0],
    ["country_id"=>28, "name"=>"Botswana","iso_code_2"=>"BW","iso_code_3"=>"BWA","status" => 0],
    ["country_id"=>29, "name"=>"Bouvet Island","iso_code_2"=>"BV","iso_code_3"=>"BVT","status" => 0],
    ["country_id"=>30, "name"=>"Brazil","iso_code_2"=>"BR","iso_code_3"=>"BRA","status" => 0],
    ["country_id"=>31, "name"=>"British Indian Ocean Territory","iso_code_2"=>"IO","iso_code_3"=>"IOT","status" => 0],
    ["country_id"=>32, "name"=>"Brunei Darussalam","iso_code_2"=>"BN","iso_code_3"=>"BRN","status" => 0],
    ["country_id"=>33, "name"=>"Bulgaria","iso_code_2"=>"BG","iso_code_3"=>"BGR","status" => 0],
    ["country_id"=>34, "name"=>"Burkina Faso","iso_code_2"=>"BF","iso_code_3"=>"BFA","status" => 0],
    ["country_id"=>35, "name"=>"Burundi","iso_code_2"=>"BI","iso_code_3"=>"BDI","status" => 0],
    ["country_id"=>36, "name"=>"Cambodia","iso_code_2"=>"KH","iso_code_3"=>"KHM","status" => 0],
    ["country_id"=>37, "name"=>"Cameroon","iso_code_2"=>"CM","iso_code_3"=>"CMR","status" => 0],
    ["country_id"=>38, "name"=>"Canada","iso_code_2"=>"CA","iso_code_3"=>"CAN","status" => 0],
    ["country_id"=>39, "name"=>"Cape Verde","iso_code_2"=>"CV","iso_code_3"=>"CPV","status" => 0],
    ["country_id"=>40, "name"=>"Cayman Islands","iso_code_2"=>"KY","iso_code_3"=>"CYM","status" => 0],
    ["country_id"=>41, "name"=>"Central African Republic","iso_code_2"=>"CF","iso_code_3"=>"CAF","status" => 0],
    ["country_id"=>42, "name"=>"Chad","iso_code_2"=>"TD","iso_code_3"=>"TCD","status" => 0],
    ["country_id"=>43, "name"=>"Chile","iso_code_2"=>"CL","iso_code_3"=>"CHL","status" => 0],
    ["country_id"=>44, "name"=>"China","iso_code_2"=>"CN","iso_code_3"=>"CHN","status" => 0],
    ["country_id"=>45, "name"=>"Christmas Island","iso_code_2"=>"CX","iso_code_3"=>"CXR","status" => 0],
    ["country_id"=>46, "name"=>"Cocos (Keeling) Islands","iso_code_2"=>"CC","iso_code_3"=>"CCK","status" => 0],
    ["country_id"=>47, "name"=>"Colombia","iso_code_2"=>"CO","iso_code_3"=>"COL","status" => 0],
    ["country_id"=>48, "name"=>"Comoros","iso_code_2"=>"KM","iso_code_3"=>"COM","status" => 0],
    ["country_id"=>49, "name"=>"Congo","iso_code_2"=>"CG","iso_code_3"=>"COG","status" => 0],
    ["country_id"=>50, "name"=>"Cook Islands","iso_code_2"=>"CK","iso_code_3"=>"COK","status" => 0],
    ["country_id"=>51, "name"=>"Costa Rica","iso_code_2"=>"CR","iso_code_3"=>"CRI","status" => 0],
    ["country_id"=>52, "name"=>"Cote D`Ivoire","iso_code_2"=>"CI","iso_code_3"=>"CIV","status" => 0],
    ["country_id"=>53, "name"=>"Croatia","iso_code_2"=>"HR","iso_code_3"=>"HRV","status" => 0],
    ["country_id"=>54, "name"=>"Cuba","iso_code_2"=>"CU","iso_code_3"=>"CUB","status" => 0],
    ["country_id"=>55, "name"=>"Cyprus","iso_code_2"=>"CY","iso_code_3"=>"CYP","status" => 0],
    ["country_id"=>56, "name"=>"Czech Republic","iso_code_2"=>"CZ","iso_code_3"=>"CZE","status" => 0],
    ["country_id"=>57, "name"=>"Denmark","iso_code_2"=>"DK","iso_code_3"=>"DNK","status" => 0],
    ["country_id"=>58, "name"=>"Djibouti","iso_code_2"=>"DJ","iso_code_3"=>"DJI","status" => 0],
    ["country_id"=>59, "name"=>"Dominica","iso_code_2"=>"DM","iso_code_3"=>"DMA","status" => 0],
    ["country_id"=>60, "name"=>"Dominican Republic","iso_code_2"=>"DO","iso_code_3"=>"DOM","status" => 0],
    ["country_id"=>61, "name"=>"East Timor","iso_code_2"=>"TL","iso_code_3"=>"TLS","status" => 0],
    ["country_id"=>62, "name"=>"Ecuador","iso_code_2"=>"EC","iso_code_3"=>"ECU","status" => 0],
    ["country_id"=>63, "name"=>"Egypt","iso_code_2"=>"EG","iso_code_3"=>"EGY","status" => 0],
    ["country_id"=>64, "name"=>"El Salvador","iso_code_2"=>"SV","iso_code_3"=>"SLV","status" => 0],
    ["country_id"=>65, "name"=>"Equatorial Guinea","iso_code_2"=>"GQ","iso_code_3"=>"GNQ","status" => 0],
    ["country_id"=>66, "name"=>"Eritrea","iso_code_2"=>"ER","iso_code_3"=>"ERI","status" => 0],
    ["country_id"=>67, "name"=>"Estonia","iso_code_2"=>"EE","iso_code_3"=>"EST","status" => 0],
    ["country_id"=>68, "name"=>"Ethiopia","iso_code_2"=>"ET","iso_code_3"=>"ETH","status" => 0],
    ["country_id"=>69, "name"=>"Falkland Islands (Malvinas)","iso_code_2"=>"FK","iso_code_3"=>"FLK","status" => 0],
    ["country_id"=>70, "name"=>"Faroe Islands","iso_code_2"=>"FO","iso_code_3"=>"FRO","status" => 0],
    ["country_id"=>71, "name"=>"Fiji","iso_code_2"=>"FJ","iso_code_3"=>"FJI","status" => 0],
    ["country_id"=>72, "name"=>"Finland","iso_code_2"=>"FI","iso_code_3"=>"FIN","status" => 0],
    ["country_id"=>74, "name"=>"France, Metropolitan","iso_code_2"=>"FR","iso_code_3"=>"FRA","status" => 0],
    ["country_id"=>75, "name"=>"French Guiana","iso_code_2"=>"GF","iso_code_3"=>"GUF","status" => 0],
    ["country_id"=>76, "name"=>"French Polynesia","iso_code_2"=>"PF","iso_code_3"=>"PYF","status" => 0],
    ["country_id"=>77, "name"=>"French Southern Territories","iso_code_2"=>"TF","iso_code_3"=>"ATF","status" => 0],
    ["country_id"=>78, "name"=>"Gabon","iso_code_2"=>"GA","iso_code_3"=>"GAB","status" => 0],
    ["country_id"=>79, "name"=>"Gambia","iso_code_2"=>"GM","iso_code_3"=>"GMB","status" => 0],
    ["country_id"=>80, "name"=>"Georgia","iso_code_2"=>"GE","iso_code_3"=>"GEO","status" => 0],
    ["country_id"=>81, "name"=>"Germany","iso_code_2"=>"DE","iso_code_3"=>"DEU","status" => 0],
    ["country_id"=>82, "name"=>"Ghana","iso_code_2"=>"GH","iso_code_3"=>"GHA","status" => 0],
    ["country_id"=>83, "name"=>"Gibraltar","iso_code_2"=>"GI","iso_code_3"=>"GIB","status" => 0],
    ["country_id"=>84, "name"=>"Greece","iso_code_2"=>"GR","iso_code_3"=>"GRC","status" => 0],
    ["country_id"=>85, "name"=>"Greenland","iso_code_2"=>"GL","iso_code_3"=>"GRL","status" => 0],
    ["country_id"=>86, "name"=>"Grenada","iso_code_2"=>"GD","iso_code_3"=>"GRD","status" => 0],
    ["country_id"=>87, "name"=>"Guadeloupe","iso_code_2"=>"GP","iso_code_3"=>"GLP","status" => 0],
    ["country_id"=>88, "name"=>"Guam","iso_code_2"=>"GU","iso_code_3"=>"GUM","status" => 0],
    ["country_id"=>89, "name"=>"Guatemala","iso_code_2"=>"GT","iso_code_3"=>"GTM","status" => 0],
    ["country_id"=>90, "name"=>"Guinea","iso_code_2"=>"GN","iso_code_3"=>"GIN","status" => 0],
    ["country_id"=>91, "name"=>"Guinea-Bissau","iso_code_2"=>"GW","iso_code_3"=>"GNB","status" => 0],
    ["country_id"=>92, "name"=>"Guyana","iso_code_2"=>"GY","iso_code_3"=>"GUY","status" => 0],
    ["country_id"=>93, "name"=>"Haiti","iso_code_2"=>"HT","iso_code_3"=>"HTI","status" => 0],
    ["country_id"=>94, "name"=>"Heard and Mc Donald Islands","iso_code_2"=>"HM","iso_code_3"=>"HMD","status" => 0],
    ["country_id"=>95, "name"=>"Honduras","iso_code_2"=>"HN","iso_code_3"=>"HND","status" => 0],
    ["country_id"=>96, "name"=>"Hong Kong","iso_code_2"=>"HK","iso_code_3"=>"HKG","status" => 0],
    ["country_id"=>97, "name"=>"Hungary","iso_code_2"=>"HU","iso_code_3"=>"HUN","status" => 0],
    ["country_id"=>98, "name"=>"Iceland","iso_code_2"=>"IS","iso_code_3"=>"ISL","status" => 0],
    ["country_id"=>99, "name"=>"India","iso_code_2"=>"IN","iso_code_3"=>"IND","status" => 0],
    ["country_id"=>100, "name"=>"Indonesia","iso_code_2"=>"ID","iso_code_3"=>"IDN","status" => 0],
    ["country_id"=>101, "name"=>"Iran (Islamic Republic of)","iso_code_2"=>"IR","iso_code_3"=>"IRN","status" => 0],
    ["country_id"=>102, "name"=>"Iraq","iso_code_2"=>"IQ","iso_code_3"=>"IRQ","status" => 0],
    ["country_id"=>103, "name"=>"Ireland","iso_code_2"=>"IE","iso_code_3"=>"IRL","status" => 0],
    ["country_id"=>104, "name"=>"Israel","iso_code_2"=>"IL","iso_code_3"=>"ISR","status" => 0],
    ["country_id"=>105, "name"=>"Italy","iso_code_2"=>"IT","iso_code_3"=>"ITA","status" => 0],
    ["country_id"=>106, "name"=>"Jamaica","iso_code_2"=>"JM","iso_code_3"=>"JAM","status" => 0],
    ["country_id"=>107, "name"=>"Japan","iso_code_2"=>"JP","iso_code_3"=>"JPN","status" => 0],
    ["country_id"=>108, "name"=>"Jordan","iso_code_2"=>"JO","iso_code_3"=>"JOR","status" => 0],
    ["country_id"=>109, "name"=>"Kazakhstan","iso_code_2"=>"KZ","iso_code_3"=>"KAZ","status" => 0],
    ["country_id"=>110, "name"=>"Kenya","iso_code_2"=>"KE","iso_code_3"=>"KEN","status" => 0],
    ["country_id"=>111, "name"=>"Kiribati","iso_code_2"=>"KI","iso_code_3"=>"KIR","status" => 0],
    ["country_id"=>112, "name"=>"North Korea","iso_code_2"=>"KP","iso_code_3"=>"PRK","status" => 0],
    ["country_id"=>113, "name"=>"South Korea","iso_code_2"=>"KR","iso_code_3"=>"KOR","status" => 0],
    ["country_id"=>114, "name"=>"Kuwait","iso_code_2"=>"KW","iso_code_3"=>"KWT","status" => 0],
    ["country_id"=>115, "name"=>"Kyrgyzstan","iso_code_2"=>"KG","iso_code_3"=>"KGZ","status" => 0],
    ["country_id"=>116, "name"=>"Lao People`s Democratic Republic","iso_code_2"=>"LA","iso_code_3"=>"LAO","status" => 0],
    ["country_id"=>117, "name"=>"Latvia","iso_code_2"=>"LV","iso_code_3"=>"LVA","status" => 0],
    ["country_id"=>118, "name"=>"Lebanon","iso_code_2"=>"LB","iso_code_3"=>"LBN","status" => 0],
    ["country_id"=>119, "name"=>"Lesotho","iso_code_2"=>"LS","iso_code_3"=>"LSO","status" => 0],
    ["country_id"=>120, "name"=>"Liberia","iso_code_2"=>"LR","iso_code_3"=>"LBR","status" => 0],
    ["country_id"=>121, "name"=>"Libyan Arab Jamahiriya","iso_code_2"=>"LY","iso_code_3"=>"LBY","status" => 0],
    ["country_id"=>122, "name"=>"Liechtenstein","iso_code_2"=>"LI","iso_code_3"=>"LIE","status" => 0],
    ["country_id"=>123, "name"=>"Lithuania","iso_code_2"=>"LT","iso_code_3"=>"LTU","status" => 0],
    ["country_id"=>124, "name"=>"Luxembourg","iso_code_2"=>"LU","iso_code_3"=>"LUX","status" => 0],
    ["country_id"=>125, "name"=>"Macau","iso_code_2"=>"MO","iso_code_3"=>"MAC","status" => 0],
    ["country_id"=>126, "name"=>"FYROM","iso_code_2"=>"MK","iso_code_3"=>"MKD","status" => 0],
    ["country_id"=>127, "name"=>"Madagascar","iso_code_2"=>"MG","iso_code_3"=>"MDG","status" => 0],
    ["country_id"=>128, "name"=>"Malawi","iso_code_2"=>"MW","iso_code_3"=>"MWI","status" => 0],
    ["country_id"=>129, "name"=>"Malaysia","iso_code_2"=>"MY","iso_code_3"=>"MYS","status" => 0],
    ["country_id"=>130, "name"=>"Maldives","iso_code_2"=>"MV","iso_code_3"=>"MDV","status" => 0],
    ["country_id"=>131, "name"=>"Mali","iso_code_2"=>"ML","iso_code_3"=>"MLI","status" => 0],
    ["country_id"=>132, "name"=>"Malta","iso_code_2"=>"MT","iso_code_3"=>"MLT","status" => 0],
    ["country_id"=>133, "name"=>"Marshall Islands","iso_code_2"=>"MH","iso_code_3"=>"MHL","status" => 0],
    ["country_id"=>134, "name"=>"Martinique","iso_code_2"=>"MQ","iso_code_3"=>"MTQ","status" => 0],
    ["country_id"=>135, "name"=>"Mauritania","iso_code_2"=>"MR","iso_code_3"=>"MRT","status" => 0],
    ["country_id"=>136, "name"=>"Mauritius","iso_code_2"=>"MU","iso_code_3"=>"MUS","status" => 0],
    ["country_id"=>137, "name"=>"Mayotte","iso_code_2"=>"YT","iso_code_3"=>"MYT","status" => 0],
    ["country_id"=>138, "name"=>"Mexico","iso_code_2"=>"MX","iso_code_3"=>"MEX","status" => 0],
    ["country_id"=>139, "name"=>"Micronesia, Federated States of","iso_code_2"=>"FM","iso_code_3"=>"FSM","status" => 0],
    ["country_id"=>140, "name"=>"Moldova, Republic of","iso_code_2"=>"MD","iso_code_3"=>"MDA","status" => 0],
    ["country_id"=>141, "name"=>"Monaco","iso_code_2"=>"MC","iso_code_3"=>"MCO","status" => 0],
    ["country_id"=>142, "name"=>"Mongolia","iso_code_2"=>"MN","iso_code_3"=>"MNG","status" => 0],
    ["country_id"=>143, "name"=>"Montserrat","iso_code_2"=>"MS","iso_code_3"=>"MSR","status" => 0],
    ["country_id"=>144, "name"=>"Morocco","iso_code_2"=>"MA","iso_code_3"=>"MAR","status" => 0],
    ["country_id"=>145, "name"=>"Mozambique","iso_code_2"=>"MZ","iso_code_3"=>"MOZ","status" => 0],
    ["country_id"=>146, "name"=>"Myanmar","iso_code_2"=>"MM","iso_code_3"=>"MMR","status" => 0],
    ["country_id"=>147, "name"=>"Namibia","iso_code_2"=>"NA","iso_code_3"=>"NAM","status" => 0],
    ["country_id"=>148, "name"=>"Nauru","iso_code_2"=>"NR","iso_code_3"=>"NRU","status" => 0],
    ["country_id"=>149, "name"=>"Nepal","iso_code_2"=>"NP","iso_code_3"=>"NPL","status" => 0],
    ["country_id"=>150, "name"=>"Netherlands","iso_code_2"=>"NL","iso_code_3"=>"NLD","status" => 0],
    ["country_id"=>151, "name"=>"Netherlands Antilles","iso_code_2"=>"AN","iso_code_3"=>"ANT","status" => 0],
    ["country_id"=>152, "name"=>"New Caledonia","iso_code_2"=>"NC","iso_code_3"=>"NCL","status" => 0],
    ["country_id"=>153, "name"=>"New Zealand","iso_code_2"=>"NZ","iso_code_3"=>"NZL","status" => 0],
    ["country_id"=>154, "name"=>"Nicaragua","iso_code_2"=>"NI","iso_code_3"=>"NIC","status" => 0],
    ["country_id"=>155, "name"=>"Niger","iso_code_2"=>"NE","iso_code_3"=>"NER","status" => 0],
    ["country_id"=>156, "name"=>"Nigeria","iso_code_2"=>"NG","iso_code_3"=>"NGA","status" => 0],
    ["country_id"=>157, "name"=>"Niue","iso_code_2"=>"NU","iso_code_3"=>"NIU","status" => 0],
    ["country_id"=>158, "name"=>"Norfolk Island","iso_code_2"=>"NF","iso_code_3"=>"NFK","status" => 0],
    ["country_id"=>159, "name"=>"Northern Mariana Islands","iso_code_2"=>"MP","iso_code_3"=>"MNP","status" => 0],
    ["country_id"=>160, "name"=>"Norway","iso_code_2"=>"NO","iso_code_3"=>"NOR","status" => 0],
    ["country_id"=>161, "name"=>"Oman","iso_code_2"=>"OM","iso_code_3"=>"OMN","status" => 0],
    ["country_id"=>162, "name"=>"Pakistan","iso_code_2"=>"PK","iso_code_3"=>"PAK","status" => 0],
    ["country_id"=>163, "name"=>"Palau","iso_code_2"=>"PW","iso_code_3"=>"PLW","status" => 0],
    ["country_id"=>164, "name"=>"Panama","iso_code_2"=>"PA","iso_code_3"=>"PAN","status" => 0],
    ["country_id"=>165, "name"=>"Papua New Guinea","iso_code_2"=>"PG","iso_code_3"=>"PNG","status" => 0],
    ["country_id"=>166, "name"=>"Paraguay","iso_code_2"=>"PY","iso_code_3"=>"PRY","status" => 0],
    ["country_id"=>167, "name"=>"Peru","iso_code_2"=>"PE","iso_code_3"=>"PER","status" => 0],
    ["country_id"=>168, "name"=>"Philippines","iso_code_2"=>"PH","iso_code_3"=>"PHL","status" => 0],
    ["country_id"=>169, "name"=>"Pitcairn","iso_code_2"=>"PN","iso_code_3"=>"PCN","status" => 0],
    ["country_id"=>170, "name"=>"Poland","iso_code_2"=>"PL","iso_code_3"=>"POL","status" => 0],
    ["country_id"=>171, "name"=>"Portugal","iso_code_2"=>"PT","iso_code_3"=>"PRT","status" => 0],
    ["country_id"=>172, "name"=>"Puerto Rico","iso_code_2"=>"PR","iso_code_3"=>"PRI","status" => 0],
    ["country_id"=>173, "name"=>"Qatar","iso_code_2"=>"QA","iso_code_3"=>"QAT","status" => 0],
    ["country_id"=>174, "name"=>"Reunion","iso_code_2"=>"RE","iso_code_3"=>"REU","status" => 0],
    ["country_id"=>175, "name"=>"Romania","iso_code_2"=>"RO","iso_code_3"=>"ROM","status" => 0],
    ["country_id"=>176, "name"=>"Russian Federation","iso_code_2"=>"RU","iso_code_3"=>"RUS","status" => 0],
    ["country_id"=>177, "name"=>"Rwanda","iso_code_2"=>"RW","iso_code_3"=>"RWA","status" => 0],
    ["country_id"=>178, "name"=>"Saint Kitts and Nevis","iso_code_2"=>"KN","iso_code_3"=>"KNA","status" => 0],
    ["country_id"=>179, "name"=>"Saint Lucia","iso_code_2"=>"LC","iso_code_3"=>"LCA","status" => 0],
    ["country_id"=>180, "name"=>"Saint Vincent and the Grenadines","iso_code_2"=>"VC","iso_code_3"=>"VCT","status" => 0],
    ["country_id"=>181, "name"=>"Samoa","iso_code_2"=>"WS","iso_code_3"=>"WSM","status" => 0],
    ["country_id"=>182, "name"=>"San Marino","iso_code_2"=>"SM","iso_code_3"=>"SMR","status" => 0],
    ["country_id"=>183, "name"=>"Sao Tome and Principe","iso_code_2"=>"ST","iso_code_3"=>"STP","status" => 0],
    ["country_id"=>184, "name"=>"Saudi Arabia","iso_code_2"=>"SA","iso_code_3"=>"SAU","status" => 0],
    ["country_id"=>185, "name"=>"Senegal","iso_code_2"=>"SN","iso_code_3"=>"SEN","status" => 0],
    ["country_id"=>186, "name"=>"Seychelles","iso_code_2"=>"SC","iso_code_3"=>"SYC","status" => 0],
    ["country_id"=>187, "name"=>"Sierra Leone","iso_code_2"=>"SL","iso_code_3"=>"SLE","status" => 0],
    ["country_id"=>188, "name"=>"Singapore","iso_code_2"=>"SG","iso_code_3"=>"SGP","status" => 0],
    ["country_id"=>189, "name"=>"Slovak Republic","iso_code_2"=>"SK","iso_code_3"=>"SVK","status" => 0],
    ["country_id"=>190, "name"=>"Slovenia","iso_code_2"=>"SI","iso_code_3"=>"SVN","status" => 0],
    ["country_id"=>191, "name"=>"Solomon Islands","iso_code_2"=>"SB","iso_code_3"=>"SLB","status" => 0],
    ["country_id"=>192, "name"=>"Somalia","iso_code_2"=>"SO","iso_code_3"=>"SOM","status" => 0],
    ["country_id"=>193, "name"=>"South Africa","iso_code_2"=>"ZA","iso_code_3"=>"ZAF","status" => 0],
    ["country_id"=>194, "name"=>"South Georgia &amp; South Sandwich Islands","iso_code_2"=>"GS","iso_code_3"=>"SGS","status" => 0],
    ["country_id"=>195, "name"=>"Spain","iso_code_2"=>"ES","iso_code_3"=>"ESP","status" => 0],
    ["country_id"=>196, "name"=>"Sri Lanka","iso_code_2"=>"LK","iso_code_3"=>"LKA","status" => 0],
    ["country_id"=>197, "name"=>"St. Helena","iso_code_2"=>"SH","iso_code_3"=>"SHN","status" => 0],
    ["country_id"=>198, "name"=>"St. Pierre and Miquelon","iso_code_2"=>"PM","iso_code_3"=>"SPM","status" => 0],
    ["country_id"=>199, "name"=>"Sudan","iso_code_2"=>"SD","iso_code_3"=>"SDN","status" => 0],
    ["country_id"=>200, "name"=>"Suriname","iso_code_2"=>"SR","iso_code_3"=>"SUR","status" => 0],
    ["country_id"=>201, "name"=>"Svalbard and Jan Mayen Islands","iso_code_2"=>"SJ","iso_code_3"=>"SJM","status" => 0],
    ["country_id"=>202, "name"=>"Swaziland","iso_code_2"=>"SZ","iso_code_3"=>"SWZ","status" => 0],
    ["country_id"=>203, "name"=>"Sweden","iso_code_2"=>"SE","iso_code_3"=>"SWE","status" => 0],
    ["country_id"=>204, "name"=>"Switzerland","iso_code_2"=>"CH","iso_code_3"=>"CHE","status" => 0],
    ["country_id"=>205, "name"=>"Syrian Arab Republic","iso_code_2"=>"SY","iso_code_3"=>"SYR","status" => 0],
    ["country_id"=>206, "name"=>"Taiwan","iso_code_2"=>"TW","iso_code_3"=>"TWN","status" => 0],
    ["country_id"=>207, "name"=>"Tajikistan","iso_code_2"=>"TJ","iso_code_3"=>"TJK","status" => 0],
    ["country_id"=>208, "name"=>"Tanzania, United Republic of","iso_code_2"=>"TZ","iso_code_3"=>"TZA","status" => 0],
    ["country_id"=>209, "name"=>"Thailand","iso_code_2"=>"TH","iso_code_3"=>"THA","status" => 0],
    ["country_id"=>210, "name"=>"Togo","iso_code_2"=>"TG","iso_code_3"=>"TGO","status" => 0],
    ["country_id"=>211, "name"=>"Tokelau","iso_code_2"=>"TK","iso_code_3"=>"TKL","status" => 0],
    ["country_id"=>212, "name"=>"Tonga","iso_code_2"=>"TO","iso_code_3"=>"TON","status" => 0],
    ["country_id"=>213, "name"=>"Trinidad and Tobago","iso_code_2"=>"TT","iso_code_3"=>"TTO","status" => 0],
    ["country_id"=>214, "name"=>"Tunisia","iso_code_2"=>"TN","iso_code_3"=>"TUN","status" => 0],
    ["country_id"=>215, "name"=>"Turkey","iso_code_2"=>"TR","iso_code_3"=>"TUR","status" => 0],
    ["country_id"=>216, "name"=>"Turkmenistan","iso_code_2"=>"TM","iso_code_3"=>"TKM","status" => 0],
    ["country_id"=>217, "name"=>"Turks and Caicos Islands","iso_code_2"=>"TC","iso_code_3"=>"TCA","status" => 0],
    ["country_id"=>218, "name"=>"Tuvalu","iso_code_2"=>"TV","iso_code_3"=>"TUV","status" => 0],
    ["country_id"=>219, "name"=>"Uganda","iso_code_2"=>"UG","iso_code_3"=>"UGA","status" => 0],
    ["country_id"=>220, "name"=>"Ukraine","iso_code_2"=>"UA","iso_code_3"=>"UKR","status" => 0],
    ["country_id"=>221, "name"=>"United Arab Emirates","iso_code_2"=>"AE","iso_code_3"=>"ARE","status" => 0],
    ["country_id"=>222, "name"=>"United Kingdom","iso_code_2"=>"GB","iso_code_3"=>"GBR","status" => 1],
    ["country_id"=>223, "name"=>"United States","iso_code_2"=>"US","iso_code_3"=>"USA","status" => 1],
    ["country_id"=>224, "name"=>"United States Minor Outlying Islands","iso_code_2"=>"UM","iso_code_3"=>"UMI","status" => 0],
    ["country_id"=>225, "name"=>"Uruguay","iso_code_2"=>"UY","iso_code_3"=>"URY","status" => 0],
    ["country_id"=>226, "name"=>"Uzbekistan","iso_code_2"=>"UZ","iso_code_3"=>"UZB","status" => 0],
    ["country_id"=>227, "name"=>"Vanuatu","iso_code_2"=>"VU","iso_code_3"=>"VUT","status" => 0],
    ["country_id"=>228, "name"=>"Vatican City State (Holy See)","iso_code_2"=>"VA","iso_code_3"=>"VAT","status" => 0],
    ["country_id"=>229, "name"=>"Venezuela","iso_code_2"=>"VE","iso_code_3"=>"VEN","status" => 0],
    ["country_id"=>230, "name"=>"Viet Nam","iso_code_2"=>"VN","iso_code_3"=>"VNM","status" => 0],
    ["country_id"=>231, "name"=>"Virgin Islands (British)","iso_code_2"=>"VG","iso_code_3"=>"VGB","status" => 0],
    ["country_id"=>232, "name"=>"Virgin Islands (U.S.)","iso_code_2"=>"VI","iso_code_3"=>"VIR","status" => 0],
    ["country_id"=>233, "name"=>"Wallis and Futuna Islands","iso_code_2"=>"WF","iso_code_3"=>"WLF","status" => 0],
    ["country_id"=>234, "name"=>"Western Sahara","iso_code_2"=>"EH","iso_code_3"=>"ESH","status" => 0],
    ["country_id"=>235, "name"=>"Yemen","iso_code_2"=>"YE","iso_code_3"=>"YEM","status" => 0],
    ["country_id"=>237, "name"=>"Democratic Republic of Congo","iso_code_2"=>"CD","iso_code_3"=>"COD","status" => 0],
    ["country_id"=>238, "name"=>"Zambia","iso_code_2"=>"ZM","iso_code_3"=>"ZMB","status" => 0],
    ["country_id"=>239, "name"=>"Zimbabwe","iso_code_2"=>"ZW","iso_code_3"=>"ZWE","status" => 0],
    ["country_id"=>242, "name"=>"Montenegro","iso_code_2"=>"ME","iso_code_3"=>"MNE","status" => 0],
    ["country_id"=>243, "name"=>"Serbia","iso_code_2"=>"RS","iso_code_3"=>"SRB","status" => 0],
    ["country_id"=>244, "name"=>"Aaland Islands","iso_code_2"=>"AX","iso_code_3"=>"ALA","status" => 0],
    ["country_id"=>245, "name"=>"Bonaire, Sint Eustatius and Saba","iso_code_2"=>"BQ","iso_code_3"=>"BES","status" => 0],
    ["country_id"=>246, "name"=>"Curacao","iso_code_2"=>"CW","iso_code_3"=>"CUW","status" => 0],
    ["country_id"=>247, "name"=>"Palestinian Territory, Occupied","iso_code_2"=>"PS","iso_code_3"=>"PSE","status" => 0],
    ["country_id"=>248, "name"=>"South Sudan","iso_code_2"=>"SS","iso_code_3"=>"SSD","status" => 0],
    ["country_id"=>249, "name"=>"St. Barthelemy","iso_code_2"=>"BL","iso_code_3"=>"BLM","status" => 0],
    ["country_id"=>250, "name"=>"St. Martin (French part)","iso_code_2"=>"MF","iso_code_3"=>"MAF","status" => 0],
    ["country_id"=>251, "name"=>"Canary Islands","iso_code_2"=>"IC","iso_code_3"=>"ICA","status" => 0],
    ["country_id"=>252, "name"=>"Ascension Island (British)","iso_code_2"=>"AC","iso_code_3"=>"ASC","status" => 0],
    ["country_id"=>253, "name"=>"Kosovo, Republic of","iso_code_2"=>"XK","iso_code_3"=>"UNK","status" => 0],
    ["country_id"=>254, "name"=>"Isle of Man","iso_code_2"=>"IM","iso_code_3"=>"IMN","status" => 0],
    ["country_id"=>255, "name"=>"Tristan da Cunha","iso_code_2"=>"TA","iso_code_3"=>"SHN","status" => 0],
    ["country_id"=>256, "name"=>"Guernsey","iso_code_2"=>"GG","iso_code_3"=>"GGY","status" => 0],
    ["country_id"=>257, "name"=>"Jersey","iso_code_2"=>"JE","iso_code_3"=>"JEY","status" => 0]

    ];

    public function __construct()
    {
        $this->kernel = new KernelCli();
        $this->container = $this->kernel->getContainer();
        $this->repository = $this->container->make(CountryRepositoryInterface::class);
    }

    public function seed(): void
    {
        $this->repository->insertMultiple($this->data);
    }
    

} 