<?php

declare(strict_types=1);

namespace App\Core\Database\seeders;

use App\Core\App\KernelCli;
use App\Core\Repositories\Order\OrderRepositoryInterface;

use Illuminate\Container\Container;

class OrderSeeder
{
    private OrderRepositoryInterface $repository;
    private KernelCli $kernel;
    private Container $container;
    private $orders = [
        [
            'order_id' => 1,
            'invoice_no' => 'INV-2024-001',
            'customer_order_id' => 'CUST-001',
            'job_id' => 1,
            'order_description' => 'Office furniture and equipment order for new branch',
            'reference_number' => 'REF-2024-001',
            'invoice_prefix' => 'INV-',
            'site_id' => 1,
            'site_name' => 'Main Office',
            'user_id' => 1,
            'user_group_id' => 1,
            'first_name' => 'John',
            'last_name' => 'Smith',
            'email' => 'john.smith@company.com',
            'phone_number' => '+61 400 123 456',
            'billing_first_name' => 'John',
            'billing_last_name' => 'Smith',
            'billing_company' => 'ABC Corporation',
            'billing_address_1' => '123 Business Street',
            'billing_address_2' => 'Suite 100',
            'billing_city' => 'Melbourne',
            'billing_post_code' => '3000',
            'billing_country_id' => 13,
            'billing_region' => 'Victoria',
            'billing_region_id' => 1,
            'payment_method' => 'Credit Card',
            'payment_data' => '{"card_type": "visa", "last4": "1234"}',
            'payment_status_id' => 1,
            'shipping_first_name' => 'John',
            'shipping_last_name' => 'Smith',
            'shipping_company' => 'ABC Corporation',
            'shipping_address_1' => '123 Business Street',
            'shipping_address_2' => 'Suite 100',
            'shipping_city' => 'Melbourne',
            'shipping_post_code' => '3000',
            'shipping_country' => 'Australia',
            'shipping_country_id' => 13,
            'shipping_region' => 'Victoria',
            'shipping_region_id' => 1,
            'shipping_method' => 'Standard Delivery',
            'shipping_data' => '{"carrier": "auspost", "tracking": "ABC123"}',
            'shipping_status_id' => 1,
            'total' => 2500.00,
            'order_status_id' => 1,
            'language_id' => 1,
            'currency_id' => 1,
            'currency' => 'AUD',
            'currency_value' => 1.00000000,
            'notes' => 'Please deliver during business hours',
            'remote_ip' => '192.168.1.100',
            'forwarded_for_ip' => '192.168.1.100',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
        ],
        [
            'order_id' => 2,
            'invoice_no' => 'INV-2024-002',
            'customer_order_id' => 'CUST-002',
            'job_id' => 2,
            'order_description' => 'Kitchen renovation materials and appliances',
            'reference_number' => 'REF-2024-002',
            'invoice_prefix' => 'INV-',
            'site_id' => 1,
            'site_name' => 'Main Office',
            'user_id' => 2,
            'user_group_id' => 1,
            'first_name' => 'Sarah',
            'last_name' => 'Johnson',
            'email' => 'sarah.johnson@company.com',
            'phone_number' => '+61 400 234 567',
            'billing_first_name' => 'Sarah',
            'billing_last_name' => 'Johnson',
            'billing_company' => 'XYZ Enterprises',
            'billing_address_1' => '456 Corporate Avenue',
            'billing_address_2' => 'Level 5',
            'billing_city' => 'Sydney',
            'billing_post_code' => '2000',
            'billing_country_id' => 13,
            'billing_region' => 'New South Wales',
            'billing_region_id' => 2,
            'payment_method' => 'Bank Transfer',
            'payment_data' => '{"bank": "commonwealth", "reference": "KITCHEN2024"}',
            'payment_status_id' => 2,
            'shipping_first_name' => 'Sarah',
            'shipping_last_name' => 'Johnson',
            'shipping_company' => 'XYZ Enterprises',
            'shipping_address_1' => '456 Corporate Avenue',
            'shipping_address_2' => 'Level 5',
            'shipping_city' => 'Sydney',
            'shipping_post_code' => '2000',
            'shipping_country' => 'Australia',
            'shipping_country_id' => 13,
            'shipping_region' => 'New South Wales',
            'shipping_region_id' => 2,
            'shipping_method' => 'Express Delivery',
            'shipping_data' => '{"carrier": "tnt", "tracking": "XYZ789"}',
            'shipping_status_id' => 2,
            'total' => 8500.00,
            'order_status_id' => 2,
            'language_id' => 1,
            'currency_id' => 1,
            'currency' => 'AUD',
            'currency_value' => 1.00000000,
            'notes' => 'Urgent delivery required for renovation project',
            'remote_ip' => '192.168.1.101',
            'forwarded_for_ip' => '192.168.1.101',
            'user_agent' => 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36'
        ],
        [
            'order_id' => 3,
            'invoice_no' => 'INV-2024-003',
            'customer_order_id' => 'CUST-003',
            'job_id' => 3,
            'order_description' => 'Bathroom fixtures and tiles for residential project',
            'reference_number' => 'REF-2024-003',
            'invoice_prefix' => 'INV-',
            'site_id' => 1,
            'site_name' => 'Main Office',
            'user_id' => 3,
            'user_group_id' => 1,
            'first_name' => 'Michael',
            'last_name' => 'Brown',
            'email' => 'michael.brown@company.com',
            'phone_number' => '+61 400 345 678',
            'billing_first_name' => 'Michael',
            'billing_last_name' => 'Brown',
            'billing_company' => 'Brown Construction',
            'billing_address_1' => '789 Industrial Road',
            'billing_address_2' => 'Unit 3',
            'billing_city' => 'Brisbane',
            'billing_post_code' => '4000',
            'billing_country_id' => 13,
            'billing_region' => 'Queensland',
            'billing_region_id' => 3,
            'payment_method' => 'Invoice',
            'payment_data' => '{"terms": "net30", "po_number": "PO-2024-001"}',
            'payment_status_id' => 3,
            'shipping_first_name' => 'Michael',
            'shipping_last_name' => 'Brown',
            'shipping_company' => 'Brown Construction',
            'shipping_address_1' => '789 Industrial Road',
            'shipping_address_2' => 'Unit 3',
            'shipping_city' => 'Brisbane',
            'shipping_post_code' => '4000',
            'shipping_country' => 'Australia',
            'shipping_country_id' => 13,
            'shipping_region' => 'Queensland',
            'shipping_region_id' => 3,
            'shipping_method' => 'Freight',
            'shipping_data' => '{"carrier": "toll", "tracking": "BROWN456"}',
            'shipping_status_id' => 3,
            'total' => 4200.00,
            'order_status_id' => 3,
            'language_id' => 1,
            'currency_id' => 1,
            'currency' => 'AUD',
            'currency_value' => 1.00000000,
            'notes' => 'Delivery to construction site - call ahead',
            'remote_ip' => '192.168.1.102',
            'forwarded_for_ip' => '192.168.1.102',
            'user_agent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36'
        ],
        [
            'order_id' => 4,
            'invoice_no' => 'INV-2024-004',
            'customer_order_id' => 'CUST-004',
            'job_id' => 4,
            'order_description' => 'Lighting fixtures for commercial office space',
            'reference_number' => 'REF-2024-004',
            'invoice_prefix' => 'INV-',
            'site_id' => 1,
            'site_name' => 'Main Office',
            'user_id' => 4,
            'user_group_id' => 1,
            'first_name' => 'Emma',
            'last_name' => 'Wilson',
            'email' => 'emma.wilson@company.com',
            'phone_number' => '+61 400 456 789',
            'billing_first_name' => 'Emma',
            'billing_last_name' => 'Wilson',
            'billing_company' => 'Wilson Design Studio',
            'billing_address_1' => '321 Creative Lane',
            'billing_address_2' => 'Studio A',
            'billing_city' => 'Perth',
            'billing_post_code' => '6000',
            'billing_country_id' => 13,
            'billing_region' => 'Western Australia',
            'billing_region_id' => 4,
            'payment_method' => 'Credit Card',
            'payment_data' => '{"card_type": "mastercard", "last4": "5678"}',
            'payment_status_id' => 1,
            'shipping_first_name' => 'Emma',
            'shipping_last_name' => 'Wilson',
            'shipping_company' => 'Wilson Design Studio',
            'shipping_address_1' => '321 Creative Lane',
            'shipping_address_2' => 'Studio A',
            'shipping_city' => 'Perth',
            'shipping_post_code' => '6000',
            'shipping_country' => 'Australia',
            'shipping_country_id' => 13,
            'shipping_region' => 'Western Australia',
            'shipping_region_id' => 4,
            'shipping_method' => 'Standard Delivery',
            'shipping_data' => '{"carrier": "auspost", "tracking": "WILSON789"}',
            'shipping_status_id' => 1,
            'total' => 1800.00,
            'order_status_id' => 1,
            'language_id' => 1,
            'currency_id' => 1,
            'currency' => 'AUD',
            'currency_value' => 1.00000000,
            'notes' => 'Energy-efficient LED fixtures preferred',
            'remote_ip' => '192.168.1.103',
            'forwarded_for_ip' => '192.168.1.103',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
        ],
        [
            'order_id' => 5,
            'invoice_no' => 'INV-2024-005',
            'customer_order_id' => 'CUST-005',
            'job_id' => 5,
            'order_description' => 'Flooring materials for retail store renovation',
            'reference_number' => 'REF-2024-005',
            'invoice_prefix' => 'INV-',
            'site_id' => 1,
            'site_name' => 'Main Office',
            'user_id' => 5,
            'user_group_id' => 1,
            'first_name' => 'David',
            'last_name' => 'Taylor',
            'email' => 'david.taylor@company.com',
            'phone_number' => '+61 400 567 890',
            'billing_first_name' => 'David',
            'billing_last_name' => 'Taylor',
            'billing_company' => 'Taylor Retail Group',
            'billing_address_1' => '654 Shopping Centre Drive',
            'billing_address_2' => 'Shop 15',
            'billing_city' => 'Adelaide',
            'billing_post_code' => '5000',
            'billing_country_id' => 13,
            'billing_region' => 'South Australia',
            'billing_region_id' => 5,
            'payment_method' => 'Bank Transfer',
            'payment_data' => '{"bank": "westpac", "reference": "RETAIL2024"}',
            'payment_status_id' => 2,
            'shipping_first_name' => 'David',
            'shipping_last_name' => 'Taylor',
            'shipping_company' => 'Taylor Retail Group',
            'shipping_address_1' => '654 Shopping Centre Drive',
            'shipping_address_2' => 'Shop 15',
            'shipping_city' => 'Adelaide',
            'shipping_post_code' => '5000',
            'shipping_country' => 'Australia',
            'shipping_country_id' => 13,
            'shipping_region' => 'South Australia',
            'shipping_region_id' => 5,
            'shipping_method' => 'Express Delivery',
            'shipping_data' => '{"carrier": "star_track", "tracking": "TAYLOR123"}',
            'shipping_status_id' => 2,
            'total' => 3200.00,
            'order_status_id' => 2,
            'language_id' => 1,
            'currency_id' => 1,
            'currency' => 'AUD',
            'currency_value' => 1.00000000,
            'notes' => 'Durable commercial-grade flooring required',
            'remote_ip' => '192.168.1.104',
            'forwarded_for_ip' => '192.168.1.104',
            'user_agent' => 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36'
        ]
    ];

    private $orderItems = [
        [
            'order_item_id' => 1,
            'language_id' => 1,
            'uuid' => '550e8400-e29b-41d4-a716-446655440001',
            'order_id' => 1,
            'product_id' => 1,
            'description' => 'Ergonomic Office Chair - Black Leather',
            'quantity' => 5,
            'unit_price' => 250.00,
            'total_price' => 1250.00,
            'photo' => '{"objectURL": "/img/design-resources/furniture/office-chair-1.png"}',
            'sort_order' => 1
        ],
        [
            'order_item_id' => 2,
            'language_id' => 1,
            'uuid' => '550e8400-e29b-41d4-a716-446655440002',
            'order_id' => 1,
            'product_id' => 2,
            'description' => 'Adjustable Standing Desk - 180cm',
            'quantity' => 3,
            'unit_price' => 350.00,
            'total_price' => 1050.00,
            'photo' => '{"objectURL": "/img/design-resources/furniture/standing-desk-1.png"}',
            'sort_order' => 2
        ],
        [
            'order_item_id' => 3,
            'language_id' => 1,
            'uuid' => '550e8400-e29b-41d4-a716-446655440003',
            'order_id' => 1,
            'product_id' => 3,
            'description' => 'LED Desk Lamp - USB Charging',
            'quantity' => 5,
            'unit_price' => 40.00,
            'total_price' => 200.00,
            'photo' => '{"objectURL": "/img/design-resources/lighting/desk-lamp-1.png"}',
            'sort_order' => 3
        ],
        [
            'order_item_id' => 4,
            'language_id' => 1,
            'uuid' => '550e8400-e29b-41d4-a716-446655440004',
            'order_id' => 2,
            'product_id' => 4,
            'description' => 'Stainless Steel Kitchen Sink - Double Bowl',
            'quantity' => 1,
            'unit_price' => 450.00,
            'total_price' => 450.00,
            'photo' => '{"objectURL": "/img/design-resources/kitchen/kitchen-sink-1.png"}',
            'sort_order' => 1
        ],
        [
            'order_item_id' => 5,
            'language_id' => 1,
            'uuid' => '550e8400-e29b-41d4-a716-446655440005',
            'order_id' => 2,
            'product_id' => 5,
            'description' => 'Gas Cooktop - 4 Burner',
            'quantity' => 1,
            'unit_price' => 650.00,
            'total_price' => 650.00,
            'photo' => '{"objectURL": "/img/design-resources/kitchen/gas-cooktop-1.png"}',
            'sort_order' => 2
        ],
        [
            'order_item_id' => 6,
            'language_id' => 1,
            'uuid' => '550e8400-e29b-41d4-a716-446655440006',
            'order_id' => 2,
            'product_id' => 6,
            'description' => 'Built-in Oven - Electric',
            'quantity' => 1,
            'unit_price' => 1200.00,
            'total_price' => 1200.00,
            'photo' => '{"objectURL": "/img/design-resources/kitchen/built-in-oven-1.png"}',
            'sort_order' => 3
        ],
        [
            'order_item_id' => 7,
            'language_id' => 1,
            'uuid' => '550e8400-e29b-41d4-a716-446655440007',
            'order_id' => 2,
            'product_id' => 7,
            'description' => 'Refrigerator - French Door',
            'quantity' => 1,
            'unit_price' => 2200.00,
            'total_price' => 2200.00,
            'photo' => '{"objectURL": "/img/design-resources/kitchen/refrigerator-1.png"}',
            'sort_order' => 4
        ],
        [
            'order_item_id' => 8,
            'language_id' => 1,
            'uuid' => '550e8400-e29b-41d4-a716-446655440008',
            'order_id' => 2,
            'product_id' => 8,
            'description' => 'Dishwasher - Integrated',
            'quantity' => 1,
            'unit_price' => 800.00,
            'total_price' => 800.00,
            'photo' => '{"objectURL": "/img/design-resources/kitchen/dishwasher-1.png"}',
            'sort_order' => 5
        ],
        [
            'order_item_id' => 9,
            'language_id' => 1,
            'uuid' => '550e8400-e29b-41d4-a716-446655440009',
            'order_id' => 2,
            'product_id' => 9,
            'description' => 'Kitchen Cabinet Set - White',
            'quantity' => 1,
            'unit_price' => 2600.00,
            'total_price' => 2600.00,
            'photo' => '{"objectURL": "/img/design-resources/kitchen/kitchen-cabinets-1.png"}',
            'sort_order' => 6
        ],
        [
            'order_item_id' => 10,
            'language_id' => 1,
            'uuid' => '550e8400-e29b-41d4-a716-446655440010',
            'order_id' => 3,
            'product_id' => 10,
            'description' => 'Ceramic Wall Tiles - White 30x60cm',
            'quantity' => 50,
            'unit_price' => 25.00,
            'total_price' => 1250.00,
            'photo' => '{"objectURL": "/img/design-resources/tiles/ceramic-tiles-1.png"}',
            'sort_order' => 1
        ],
        [
            'order_item_id' => 11,
            'language_id' => 1,
            'uuid' => '550e8400-e29b-41d4-a716-446655440011',
            'order_id' => 3,
            'product_id' => 11,
            'description' => 'Porcelain Floor Tiles - Grey 60x60cm',
            'quantity' => 30,
            'unit_price' => 45.00,
            'total_price' => 1350.00,
            'photo' => '{"objectURL": "/img/design-resources/tiles/porcelain-tiles-1.png"}',
            'sort_order' => 2
        ],
        [
            'order_item_id' => 12,
            'language_id' => 1,
            'uuid' => '550e8400-e29b-41d4-a716-446655440012',
            'order_id' => 3,
            'product_id' => 12,
            'description' => 'Bathroom Vanity - Double Sink',
            'quantity' => 1,
            'unit_price' => 850.00,
            'total_price' => 850.00,
            'photo' => '{"objectURL": "/img/design-resources/bathroom/vanity-1.png"}',
            'sort_order' => 3
        ],
        [
            'order_item_id' => 13,
            'language_id' => 1,
            'uuid' => '550e8400-e29b-41d4-a716-446655440013',
            'order_id' => 3,
            'product_id' => 13,
            'description' => 'Shower Screen - Frameless',
            'quantity' => 1,
            'unit_price' => 750.00,
            'total_price' => 750.00,
            'photo' => '{"objectURL": "/img/design-resources/bathroom/shower-screen-1.png"}',
            'sort_order' => 4
        ],
        [
            'order_item_id' => 14,
            'language_id' => 1,
            'uuid' => '550e8400-e29b-41d4-a716-446655440014',
            'order_id' => 4,
            'product_id' => 14,
            'description' => 'LED Panel Light - 60x60cm',
            'quantity' => 8,
            'unit_price' => 120.00,
            'total_price' => 960.00,
            'photo' => '{"objectURL": "/img/design-resources/lighting/led-panel-1.png"}',
            'sort_order' => 1
        ],
        [
            'order_item_id' => 15,
            'language_id' => 1,
            'uuid' => '550e8400-e29b-41d4-a716-446655440015',
            'order_id' => 4,
            'product_id' => 15,
            'description' => 'Track Lighting Kit - 6 Heads',
            'quantity' => 2,
            'unit_price' => 420.00,
            'total_price' => 840.00,
            'photo' => '{"objectURL": "/img/design-resources/lighting/track-lighting-1.png"}',
            'sort_order' => 2
        ],
        [
            'order_item_id' => 16,
            'language_id' => 1,
            'uuid' => '550e8400-e29b-41d4-a716-446655440016',
            'order_id' => 5,
            'product_id' => 16,
            'description' => 'Vinyl Flooring - Commercial Grade',
            'quantity' => 100,
            'unit_price' => 18.00,
            'total_price' => 1800.00,
            'photo' => '{"objectURL": "/img/design-resources/flooring/vinyl-flooring-1.png"}',
            'sort_order' => 1
        ],
        [
            'order_item_id' => 17,
            'language_id' => 1,
            'uuid' => '550e8400-e29b-41d4-a716-446655440017',
            'order_id' => 5,
            'product_id' => 17,
            'description' => 'Carpet Tiles - 50x50cm',
            'quantity' => 80,
            'unit_price' => 17.50,
            'total_price' => 1400.00,
            'photo' => '{"objectURL": "/img/design-resources/flooring/carpet-tiles-1.png"}',
            'sort_order' => 2
        ]
    ];

    public function __construct()
    {
        $this->kernel = new KernelCli();
        $this->container = $this->kernel->getContainer();
        $this->repository = $this->container->make(OrderRepositoryInterface::class);
    }

    public function seed(): void
    {
        $this->repository->insertOrders(['orders' => $this->orders, 'orderItems' => $this->orderItems]);
    }
    

} 